#ifndef VERSION_H
#define VERSION_H


#define VERSION_MAJOR_NUMBER 1
#define VERSION_MEDIUM_NUMBER 0
#define VERSION_MINOR_NUMBER 0
#define VERSION_BUILD_NUMBER 50

#define VERSION QString("V %1.%2.%3.%4").arg(VERSION_MAJOR_NUMBER) \
         .arg(VERSION_MEDIUM_NUMBER) \
         .arg(VERSION_MINOR_NUMBER).arg(VERSION_BUILD_NUMBER)

#endif //VERSION_H
